version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./vol_source:/vol_source
     - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./config/php    
    volumes:
     - ./vol_source:/vol_source
     - ./vol_tmp:/tmp  
     - ./vol_config/php.ini:/user/local/etc/php/conf.d/php.ini
    links:
     - db:mysql
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: 'shopware'
      MYSQL_USER: 'shopware'
      MYSQL_PASSWORD: 'shopware'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - ./vol_database:/var/lib/mysql
