version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./vol_source:/vol_source
     - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
     - php
    container_name: your_ngninx_container
  php:
    build: ./config/php    
    volumes:
     - ./vol_source:/vol_source
     - ./vol_tmp:/tmp  
     - ./vol_config/php.ini:/user/local/etc/php/conf.d/php.ini
    links:
     - db:mysql
    container_name: your_php_container
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_USER: 'project'
      MYSQL_PASSWORD: 'project'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - ./vol_database:/var/lib/mysql
    container_name: your_db_container
